### ISSUE TITLE
CDFI inference speed

### ISSUE THREAD

**Issue by qhdqhd** [tding1/CDFI#18]
What is the CDFI inference speed and what is FPS in 1080P video? Why is it slower than AdaCof when I see somebody's evaluation? Isn't it that the CDFI compression model is smaller and faster?

**Comment by tding1** [comment]
The inference speed is highly dependent on the hardware resources. CDFI might be slower than the original AdaCof since we have added new components on top of the compressed AdaCof, which might be time consuming. However, the compressed AdaCof itself is definitely smaller and faster than the original AdaCof.

**Comment by qhdqhd** [comment]
Update： 
GPU: 1080Ti 
resolution 1280X720  
about 1.5s/frame
