### ISSUE TITLE
LPIPS computation issue

### ISSUE THREAD

**Issue by hzwer** [tding1/CDFI#6]
https://github.com/tding1/CDFI/blob/0de1f7eaa79e6f3ad7c0e9d6ad4a9f7fba891e9e/test.py#L123

You seem to use ‘squeeze net’ when testing lpips index, which may cause some problems with your Table 3 comparison experiment.

The results reported by Softsplat are consistent with EDSC, but your reported EDSC results cannot be consistent with the origin EDSC paper (refer to https://arxiv.org/pdf/2006.08070.pdf Table 4). In your paper, the LPIPS of EDSC is much better than SoftSplat. CAIN and EDSC are better than DAIN, which is counter-common sense. This makes this part of the data look very strange.

I suggest modifying this part of the data so that future researchers can follow your work well. Thank you very much.

From EDSC:
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/10103856/114151082-560b9d80-994f-11eb-8dda-53d01449f33e.png">

From CDFI: 
<img width="963" alt="image" src="https://user-images.githubusercontent.com/10103856/114151163-6cb1f480-994f-11eb-8ce1-1c113b95f1d8.png">

**Comment by tding1** [comment]
Thanks for asking this question. 

> The results reported by Softsplat are consistent with EDSC

Note that Softsplat (03/11/2020 in arxiv) is published **earlier** than EDSC (06/15/2020), so it is the results of EDSC consistent with Softsplat, not the other way around. In fact, since Softsplat is closed-source, EDSC copied their quantitative results into their Table 5 in the EDSC paper.



> You seem to use ‘squeeze net’ when testing lpips index, which may cause some problems with your Table 3 comparison experiment.

> I suggest modifying this part of the data so that future researchers can follow your work well. Thank you very much.

This is a great question. However, it seems that we are the first to explicitly show how to compute LPIPS in the code. DAIN is open-source but without computing LPIPS in their work. Softsplat is closed-source, EDSC is open-source (see [here](https://github.com/Xianhang/EDSC-pytorch)), but neither do they clearly demonstrate (in their paper or code) how to compute LPIPS, e.g., using squeeze net or something else. Given this obscure context, we explicitly open source our code for computing LPIPS, and with the hope that future researchers can follow this practice.

**Comment by hzwer** [comment]
I don't mind if you use squeeze net. What I mean is that there are different calculation methods for lpips in one of your tables, which will make the data look very strange.
I have tested this index. I think most of the papers are measured by alexnet. I can reproduce their reported result using code from lpips author: https://github.com/richzhang/PerceptualSimilarity/blob/cbbf94591cce023ddbf7c3a489d4e6d22bd9f36a/lpips_2imgs.py#L13
There are many other codes that can be referred to:
other repos：
https://github.com/kingsj0405/ciplab-NTIRE-2020/blob/1cbc5ced17d6b9b4ce09fff80d64328d63be3b66/train.py#L56
https://github.com/clovaai/stargan-v2/blob/2a74f3dcd7ad3d1f7f018e7d97bd7622787acc16/metrics/lpips.py#L20

为了准确表达希望大佬不介意我用中文说几句，插帧这个领域确实比较小众，所以各种指标测试困难，FLAVR 似乎因为数据测错从 cvpr21 撤稿了，所以 CDFI 有一些瑕疵不算啥
在相关的图像重建大领域中，测 lpips 的方式应该是统一的，可以找到很多超分、denoise 相关代码
您如果决定自己选择一种独特的测 lpips 的方法，我的简单建议就是你把引用 EDSC 的几个数据去掉，不然一个表里有两种测 lpips 方法得到的指标，相对值看着非常怪异
换种说法，如果您要引用 EDSC 的表格，加上一些自己的数据，您的测试方法应该向 EDSC 靠拢，用 lpips 的默认测试脚本即可；EDSC 作者人很好，需要帮助可以给他发邮件；SoftSplat 的结果可以在作者主页下载到
利益相关：我在工业界做了几年图像质量相关工作，我的经验是 Vimeo90k 的 lpips 刷到 0.015 就非常好了，所以才会来研究一下 CDFI 是怎么得到 0.010 的

**Comment by tding1** [comment]
@hzwer 谢谢你的提醒！其实我对于其他领域如何测lpips并不清楚，而且本身也是初次涉足插帧领域，当时看到其他插帧文章以及代码并没有关于lpips的调用细节，所以选择了特定的一个type，手动测了有限的几个开源的代码结果。如果说这些文章原始实现默认用的都是alexnet（基于推测）而我用squeeze net对它们重新测试造成了差异，我会在arxiv更新一个版本，在正文和表格里加上说明，明确我这里的lpips的实验结果（AdaCoF, EDSC, CAIN, CDFI）是基于squeeze net，而它们原文章的实验结果（Softsplat, EDSC）很可能是alexnet，以避免后来者误会。
